### ISSUE TITLE
[Bug]在部分MCDR插件中无法通过[+X]来添加xaero小地图路径点

### ISSUE THREAD

**Issue by qwe4559999** [Fallen-Breath/LetMeClickAndSendForServer#1]
### Bug description

![2024-12-04_01 08 56](https://github.com/user-attachments/assets/49c89090-5e56-4db7-8273-d16d3ebf650f)
如图所示，在使用where2go插件的!!here指令时无法创建xaero路径点，而是表现为在聊天栏发送消息

### Steps to reproduce

1.使用可以添加xaero路径点的MCDR插件（例如here或者where2go）
2.使用指令（例如!!here）
3.[+x]可以点击，但是无法正确创建xaero路径点，在聊天栏中出现本应传递给xaero的命令

### Expected behavior

1.使用可以添加xaero路径点的xaero插件（例如here或者where2go）
2.使用指令（例如!!here）
3.[+x]可以点击，可以正确出现xaero创建路径点对话框

### Actual behavior

如复现步骤所述

### Minecraft version

1.20.4

### Let Me Click And Send for Server version

1.0.0

### Other information

其它有关mod信息：
[Xaero的小地图] Xaeros_Minimap_24.6.1_Fabric_1.20.4
[Xaero的世界地图] XaerosWorldMap_1.39.0_Fabric_1.20.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
与本 mod 无关。本 mod 是纯服务端模组，不影响客户端 mod 的运作逻辑。该不可用的还是不可用

**Comment by qwe4559999** [comment]
使用LetMeClickAndSend-v1.1.1-mc1.20.1-fabric这一客户端模组，并使用更旧版本的xaero小地图则无此问题

**Comment by Fallen-Breath** [comment]
> 使用LetMeClickAndSend-v1.1.1-mc1.20.1-fabric这一客户端模组，并使用更旧版本的xaero小地图则无此问题

请理解本 mod 的功能，包括但不限于阅读本仓库的 README。所述表现是预期内现象

**Comment by Fallen-Breath** [comment]
点击被本 mod 处理完后的消息，看到的“发送的”聊天消息，是服务端模拟输出的文本，而不是客户端发送的真实消息。因此任何依赖客户端直接发出消息的 mod 都可以无法正常工作。若有需求，请使用客户端版 mod
